import type { Metadata } from "next";
import Footer from "@/components/footer";
import "./globals.css";
import { HeroHeader } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeroHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
